### ISSUE TITLE
Error occurred while enabling LoreBlocks v1.0

### ISSUE THREAD

**Issue by andris155** [TealNerd/LoreBlocks#1]
```
[18:32:11] [Server thread/ERROR]: Error occurred while enabling LoreBlocks v1.0 (Is it up to date?)
java.lang.ExceptionInInitializerError
    at com.biggestnerd.loreblocks.BlockListener.<init>(BlockListener.java:37) ~[?:?]
    at com.biggestnerd.loreblocks.LoreBlocks.onEnable(LoreBlocks.java:19) ~[?:?]
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292) ~[patched_1.9.4.jar:git-Paper-736]
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:319) [patched_1.9.4.jar:git-Paper-736]
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [patched_1.9.4.jar:git-Paper-736]
    at org.bukkit.craftbukkit.v1_9_R2.CraftServer.loadPlugin(CraftServer.java:357) [patched_1.9.4.jar:git-Paper-736]
    at org.bukkit.craftbukkit.v1_9_R2.CraftServer.enablePlugins(CraftServer.java:317) [patched_1.9.4.jar:git-Paper-736]
    at net.minecraft.server.v1_9_R2.MinecraftServer.t(MinecraftServer.java:419) [patched_1.9.4.jar:git-Paper-736]
    at net.minecraft.server.v1_9_R2.MinecraftServer.l(MinecraftServer.java:384) [patched_1.9.4.jar:git-Paper-736]
    at net.minecraft.server.v1_9_R2.MinecraftServer.a(MinecraftServer.java:338) [patched_1.9.4.jar:git-Paper-736]
    at net.minecraft.server.v1_9_R2.DedicatedServer.init(DedicatedServer.java:272) [patched_1.9.4.jar:git-Paper-736]
    at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:578) [patched_1.9.4.jar:git-Paper-736]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_92]
Caused by: java.util.regex.PatternSyntaxException: Illegal repetition near index 8
^Location{world=(.*),x=([-]?[0-9]+\.?[0-9]*?),y=([-]?[0-9]+\.?[0-9]*?),z=([-]?[0-9]+\.?[0-9]*?),.*}$
        ^
    at java.util.regex.Pattern.error(Unknown Source) ~[?:1.8.0_92]
    at java.util.regex.Pattern.closure(Unknown Source) ~[?:1.8.0_92]
    at java.util.regex.Pattern.sequence(Unknown Source) ~[?:1.8.0_92]
    at java.util.regex.Pattern.expr(Unknown Source) ~[?:1.8.0_92]
    at java.util.regex.Pattern.compile(Unknown Source) ~[?:1.8.0_92]
    at java.util.regex.Pattern.<init>(Unknown Source) ~[?:1.8.0_92]
    at java.util.regex.Pattern.compile(Unknown Source) ~[?:1.8.0_92]
    at com.biggestnerd.loreblocks.LoreBlockDAO.<clinit>(LoreBlockDAO.java:55) ~[?:?]
    ... 13 more
```

**Comment by TealNerd** [comment]
fixed c049279
